name: BillPro
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "15.0"
packages: {}
targets:
  BillPro:
    type: application
    platform: iOS
    sources:
      - path: BillPro
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.khanh.billpro
        INFOPLIST_FILE: BillPro/Info.plist
        SWIFT_VERSION: 5.9
        IPHONEOS_DEPLOYMENT_TARGET: 15.0
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
    scheme:
      testTargets: []
