default_platform(:ios)
platform :ios do
  lane :build_unsigned do
    sh %(xcodegen generate)
    sh %(xcodebuild -project BillPro.xcodeproj -scheme BillPro -configuration Release -sdk iphoneos CODE_SIGNING_ALLOWED=NO build)
  end
end
