name: Build iOS 15 IPA (TrollStore)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Remove old .xcodeproj if exists
        run: rm -rf BillPro.xcodeproj

      - name: Install tools (Mint + ldid)
        run: |
          brew update
          brew install mint ldid

      - name: Generate Xcode project with XcodeGen 2.43.0 (via Mint)
        run: |
          mint run yonaskolb/XcodeGen@2.43.0 xcodegen version
          mint run yonaskolb/XcodeGen@2.43.0 xcodegen generate

      - name: Force downgrade project format to Xcode 15 (fallback)
        run: |
          PBX=BillPro.xcodeproj/project.pbxproj
          test -f "$PBX" || { echo "missing $PBX"; exit 1; }
          /usr/bin/perl -pi -e 's/objectVersion = 7[6-9];/objectVersion = 75;/g' "$PBX"
          /usr/bin/perl -pi -e 's/compatibilityVersion = "Xcode 1[6-9](\.0)?";/compatibilityVersion = "Xcode 15.0";/g' "$PBX"
          echo "---- objectVersion ----"; grep -m1 'objectVersion' "$PBX" || true
          echo "---- compatibilityVersion ----"; grep -m1 'compatibilityVersion' "$PBX" || true

      - name: Build .app (no signing, save & print logs)
        run: |
          set -x
          touch build.log
          echo "=== xcodebuild -list ===" | tee -a build.log
          xcodebuild -list -project BillPro.xcodeproj 2>&1 | tee -a build.log
          echo "=== SHOW BUILD SETTINGS ===" | tee -a build.log
          xcodebuild -showBuildSettings -project BillPro.xcodeproj -scheme BillPro 2>&1 | tee -a build.log || true
          echo "=== START BUILD ===" | tee -a build.log
          set +e
          set -o pipefail
          xcodebuild -project BillPro.xcodeproj -scheme BillPro -configuration Release -sdk iphoneos             IPHONEOS_DEPLOYMENT_TARGET=15.0 CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO             build 2>&1 | tee -a build.log
          echo "BUILD_EXIT_CODE=$?" | tee -a build.log
          set -e

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      - name: Find built app
        id: findapp
        run: |
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "BillPro.app" -type d | head -n 1)
          echo "APP_PATH=$APP_PATH"
          echo "APP_PATH=$APP_PATH" >> $GITHUB_OUTPUT

      - name: Ad-hoc sign with ldid (TrollStore)
        run: |
          mkdir -p signed
          cp -R "${{ steps.findapp.outputs.APP_PATH }}" signed/BillPro.app
          cat > signed/entitlements.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>application-identifier</key><string>com.example.BillPro</string>
            <key>get-task-allow</key><true/>
            <key>keychain-access-groups</key><array><string>com.example.BillPro</string></array>
          </dict>
          </plist>
          PLIST
          ldid -Ssigned/entitlements.plist signed/BillPro.app

      - name: Package IPA
        run: |
          mkdir -p Payload
          cp -R signed/BillPro.app Payload/
          zip -r BillPro_iOS15_TrollStore.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: BillPro-iOS15-IPA
          path: BillPro_iOS15_TrollStore.ipa
