name: Build iOS 15 IPA (TrollStore)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: |
          brew update
          brew install xcodegen ldid
      - name: Generate Xcode project
        run: xcodegen generate
      - name: Build .app (no signing, with logs)
        run: |
          set -x
          xcodebuild -list
          set +e
          xcodebuild -project BillPro.xcodeproj -scheme BillPro -configuration Release -sdk iphoneos \
            IPHONEOS_DEPLOYMENT_TARGET=15.0 CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
            build | tee build.log
          echo "BUILD_EXIT_CODE=$?" >> $GITHUB_ENV
          set -e
      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
      - name: Find built app
        id: findapp
        run: |
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "BillPro.app" -type d | head -n 1)
          echo "APP_PATH=$APP_PATH" >> $GITHUB_OUTPUT
      - name: Ad-hoc sign with ldid (TrollStore)
        run: |
          mkdir -p signed
          cp -R "${{ steps.findapp.outputs.APP_PATH }}" signed/BillPro.app
          # Minimal entitlements for TrollStore permasigning
          cat > signed/entitlements.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>application-identifier</key><string>com.example.BillPro</string>
            <key>get-task-allow</key><true/>
            <key>keychain-access-groups</key><array><string>com.example.BillPro</string></array>
          </dict>
          </plist>
          PLIST
          ldid -Ssigned/entitlements.plist signed/BillPro.app
      - name: Package IPA
        run: |
          mkdir -p Payload
          cp -R signed/BillPro.app Payload/
          zip -r BillPro_iOS15_TrollStore.ipa Payload
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: BillPro-iOS15-IPA
          path: BillPro_iOS15_TrollStore.ipa
